import Head from 'next/head';
import Logo from '../components/logo/Logo';
import Header from '../components/header/Header';
import Footer from '../components/footer/Footer';
import NavMenu from '../components/header/NavMenu';
import Splash from '../components/Splash';
import Profile from '../components/profile/Profile';
import { Section } from '../components/base/base';
import Projects from '../components/projects/projects';
export default function Home() {
  return (
    <div className='home_container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header><Logo/><NavMenu/></Header>
      <main >
        <Section><Splash/></Section>
        <Section><Profile/></Section>
        <Section><Projects/></Section>
        <Section style={{height: 700, width: "100%"}}/>
      </main>
    </div>
  );
}
