import { navItems } from '../data/nav';
import Head from 'next/head';
import Logo from '../components/logo/Logo';
import Header from '../components/header/Header';
import NavMenu from '../components/header/NavMenu/NavMenu';
import Splash from '../components/Splash';
import Profile from '../components/profile/Profile';
import { Section } from '../components/base/base';
import {Spacer} from '../components/base/Spacer';
import Work from '../components/work/Work';
import FooterCTA from '../components/footer/FooterCTA';
import Footer from '../components/footer/Footer';
import useOnLoadAnimation from '../components/animation/onPageLoad/useOnLoadAnimation';

export default function Home() {
  const onLoadAnimations = useOnLoadAnimation({navItems: navItems.map(item=> item.name)});
  return (
    <div className='home_container'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header><Logo/><NavMenu items={navItems} animation={onLoadAnimations.nav}/></Header>
      <main >
        <Section id="splash" style={{marginBottom: 0}}>
          <Splash animation={onLoadAnimations.splash}/>
        </Section>
        <Section id="who"><Profile/></Section>
        <Section id="work"><Work/></Section>
      </main>
      <Footer id="contact"><FooterCTA /></Footer>
      <Spacer height="82px" width={"100%"}  />
    </div>
  );
}
