import { navData } from '../../data/planning/nav';
import Head from 'next/head';
import Logo from '../../components/logo/Logo';
import Header from '../../components/header/Header';
import NavMenu from '../../components/header/NavMenu/NavMenu';
import { Section } from '../../components/base/base';

import Footer from '../../components/footer/Footer';

export default function Home() {

  return (
    <div className='home_container'>
      <Head>
        <title>Connected Planning</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"></meta>
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png" />
        <link rel="manifest" href="/site.webmanifest"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header background="#FFFFF">
          <Logo/>
          <NavMenu 
            items={navData} 
          />
        </Header>
        <main >
          <Section >
            {/* <Profile  /> */}
          </Section>
          
        </main>
        <Footer >
          <div>Hire me Yo!</div>
        </Footer>
    </div>
  );
}
